### ISSUE TITLE
冲到99就停止充电

### ISSUE THREAD

**Issue by hangyang555** [chase535/accurate_battery#47]
![Screenshot_2023-02-16-22-11-23-825_com omarea vtools](https://user-images.githubusercontent.com/103406049/219390952-aee251da-f23b-4471-9a07-ad9fea5453f2.jpg)
如图和题所示

**Comment by chase535** [comment]
不是程序问题，但理论上可以修复，不过还需要您的帮助。当电量固定在这个值的时候，/sys/class/power_supply/battery/current_now文件的值是多少？如果非0的话，那这个值会随着时间的推移而减小直到变为0吗？


目前确实收到较多此类问题的反馈，且据部分反馈是概率性问题，我认为这是系统bug。scene中读取到的“98.87”即为精准电量程序所读取到的真实电量，只不过程序将此值四舍五入为整数并写入了UI电量的文件，若此数值固定在了98.87，那么程序所取的整数就固定在99。程序并未对“98.87”这个文件做任何修改，只是读取数值，无论如何也不会导致此文件数值固定不变，所以得出“是系统bug”这个结论。

**Comment by hangyang555** [comment]
正在给手机充电，我这里还有一张图，是没刷的时候的
![Screenshot_2023-02-12-22-41-17-231_com omarea vtools](https://user-images.githubusercontent.com/103406049/219402921-e1616990-f454-41c3-83b0-12628d2bf39d.jpg)
(相差2)也就是说放手机提示100的时候实际电量就是98左右，没刷的时候

**Comment by hangyang555** [comment]
![Uploading Screenshot_2023-02-12-15-54-38-520_com.omarea.vtools.jpg…]()

**Comment by hangyang555** [comment]
放错了

**Comment by hangyang555** [comment]
我还有一张图，是没刷的时候的，电量相差二，也就是说当手机提示100的时候就是98左右
![Uploading Screenshot_2023-02-12-15-54-38-520_com.omarea.vtools.jpg…]()

**Comment by hangyang555** [comment]
![Uploading Screenshot_2023-02-12-15-54-38-520_com.omarea.vtools.jpg…]()

**Comment by chase535** [comment]
这就解释得通了，真实电量文件一直卡在98.几，可是手机已经充满了，没用模块的时候可以显示100，可是用了模块后因为读取的是那个文件，反而显示不了。一会给一下数据，还有充满拔下充电器后scene中显示的是98.几还是100

**Comment by hangyang555** [comment]
系统为miui14.0.0.3可能暂时无法复现，等涓流充电结束看看
![Screenshot_2023-02-16-23-19-10-442_com omarea vtools](https://user-images.githubusercontent.com/103406049/219408854-297981f8-0113-4d1c-90e8-95ad8cc779cd.jpg)

**Comment by hangyang555** [comment]
14.0.3.0

**Comment by hangyang555** [comment]
半复现，确认为0
![Screenshot_2023-02-16-23-31-27-611_com omarea vtools](https://user-images.githubusercontent.com/103406049/219412052-92e08b62-a8fe-4f4c-8dcc-85854245f8a0.jpg)
![Screenshot_2023-02-16-23-31-23-145_bin mt plus](https://user-images.githubusercontent.com/103406049/219412070-a6ead496-2c06-45ee-8286-5991630d4a98.jpg)

**Comment by chase535** [comment]
这一次复现不了也没事，肯定有机会复现🤣


明天会处理一下，拟解决这个问题，但想要正式解决还是需要那些数据

**Comment by chase535** [comment]
那拔下充电器后是98.98吗？

**Comment by hangyang555** [comment]
是的

**Comment by chase535** [comment]
[试试这个](https://github.com/chase535/accurate_battery/actions/runs/4201919624)，因为并没有修改精准电量那个98.几的文件，所以ui电量会和scene中显示的电量有出入

**Comment by hangyang555** [comment]
很抱歉最近没有回复，经测试好了
![Uploading Screenshot_2023-02-20-22-31-16-984_com.omarea.vtools.jpg…]()

**Comment by chase535** [comment]
好的，准备发布新版
