### ISSUE TITLE
[BUG] 不支持小米12 Pro 即便文件已存在

### ISSUE THREAD

**Issue by Flyrder** [chase535/accurate_battery#57]
### 版本要求

- [X] 我正在使用[Releases](https://github.com/chase535/turbo-charge/releases)中的最新版本

### 复现步骤

![Screenshot_2024-02-10-10-48-08-318_bin mt plus](https://github.com/chase535/accurate_battery/assets/106471753/5dadcf3f-9d46-403a-87ad-29ec22be1c36)
环境 KSU 11458 不能安装

### 预期行为

文件已存在

### 实际行为

It dont works
![Screenshot_2024-02-10-10-49-40-478_me weishu kernelsu](https://github.com/chase535/accurate_battery/assets/106471753/3541cbca-70f2-432d-ab1d-790032484343)

### 安卓版本

A14

### 手机系统及版本

24.1.26 SkyMi官改

**Comment by chase535** [comment]
新年快乐！没有real_capacity或capacity_raw，这个文件存储着BMS芯片计算得出的真实电量值，需要读取这个文件的值然后写入到系统读取电量的文件capacity，capacity这个文件也是UI电量读取的文件
